require 'temp_app_loader'

module ApplicationTests
  class CoverageTest < SpoutAppTestCase

    include TestHelpers::Paths
    include TestHelpers::Generation

    def setup
      build_app
      app_file '.spout.yml', <<-YML
        visit: visit
        charts: []
      YML
    end

    def teardown
      teardown_app
    end

    def test_coverage
      Dir.chdir(app_path) { Spout.launch(['coverage', '--console']) }

      index_file = File.read(File.join(app_path, 'coverage', 'index.html')) rescue nil
      assert_not_nil index_file

      assert_match /<title>Spout Coverage<\/title>/, index_file
      assert_match /Generated by <a href=\"https\:\/\/github.com\/sleepepi\/spout\">Spout<\/a> v#{Spout::VERSION::STRING}/, index_file
    end

    def test_no_csvs_for_coverage_report
      Dir.chdir(app_path) { Spout.launch(['coverage', '--console']) }

      index_file = File.read(File.join(app_path, 'coverage', 'index.html')) rescue nil
      assert_not_nil index_file

      assert_match /No CSVs found in <code>#{app_path}\/csvs\/1.0.0\/<\/code>/, index_file
    end

    def test_no_csvs_for_coverage_report_with_version_file
      app_file 'VERSION', <<-SCRIPT
        0.1.0.beta5
      SCRIPT

      Dir.chdir(app_path) { Spout.launch(['coverage', '--console']) }

      index_file = File.read(File.join(app_path, 'coverage', 'index.html')) rescue nil
      assert_not_nil index_file

      assert_match /No CSVs found in <code>#{app_path}\/csvs\/0.1.0.beta5\/<\/code>/, index_file

      delete_app_file 'VERSION'
    end

  end
end
